---
- name: (libvirt) set qemu_user fact
  set_fact:
    qemu_user: '{{ arch_user|default(ansible_user) }}'

- become: yes
  block:
    - name: (libvirt) install necessary packages
      pacman:
        name: '{{ item }}'
        state: present
        extra_args: '--ask 4'
      with_items:
        - archlinux-keyring
        - qemu-desktop
        - libvirt
        - edk2-ovmf
        - virt-manager
        - iptables-nft
        - dnsmasq
        - swtpm

    - name: (libvirt) enable libvirt on system boot
      service:
        name: libvirtd.service
        enabled: true
        state: started

    - name: (libvirt) enable default libvirt network
      shell: virsh net-autostart default && virsh net-start default
      failed_when: false

    - name: (libvirt) add group libvirt to user {{ qemu_user }}
      shell: usermod -aG libvirt {{ qemu_user }}

    - name: (libvirt) configure qemu permissions
      lineinfile:
        dest: /etc/libvirt/qemu.conf
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      with_items:
        - { regexp: '#group = "root"', line: 'group = "libvirt"' }
        - { regexp: '#user = "root"', line: 'user = "{{ qemu_user }}"' }
      when: kvm_fix_permissions|default(false) == true

    - when: tpm_fix_permissions|default(false) == true
      block:
        - name: (libvirt) configure swtpm permissions
          lineinfile:
            dest: /etc/libvirt/qemu.conf
            regexp: '{{ item.regexp }}'
            line: '{{ item.line }}'
          with_items:
            - { regexp: '#swtpm_user = "tss"', line: 'swtpm_user = "tss"' }
            - { regexp: '#swtpm_group = "tss"', line: 'swtpm_group = "tss"' }

        - name: (libvirt) fix swtpm directory permissions
          file:
            path: /var/lib/swtpm-localca
            owner: tss
            group: tss

    - name: (libvirt) restart libvirt service
      service:
        name: libvirtd.service
        state: restarted
