#!/usr/bin/env bash

case "${1}" in
  debug|dbg)
    sudo dmesg | grep -i -e DMAR -e IOMMU
    ;;
  groups)
    shopt -s nullglob
    for g in `find /sys/kernel/iommu_groups/* -maxdepth 0 -type d | sort -V`; do
        echo "IOMMU Group ${g##*/}:"
        for d in $g/devices/*; do
            echo -e "\t$(lspci -nns ${d##*/})"
        done;
    done;
    ;;
  *)
    cat <<EOF
usage:
  iommu [ACTION]
ACTIONS:
    debug
        Filter dmesg output for IOMMU
    groups
        Shows a list of IOMMU groups and their devicies
EOF
    ;;
esac
