---
- when: gpu_vendor is defined
  become: yes
  block:
    - name: (GPU) install Intel driver
      pacman:
        name: xf86-video-intel
        state: present
      when: gpu_vendor == 'intel'

    - when: gpu_vendor == 'nvidia'
      block:
        - when: gpu_nvidia_proprietary|default(true) == true
          block:
            - name: (GPU) blacklist open source driver (nouveau)
              copy:
                content: 'blacklist nouveau'
                dest: /etc/modprobe.d/blacklist.conf

            - name: (GPU) install proprietary driver
              pacman:
                name: nvidia
                state: present
              when: gpu_nvidia_dkms|default(false) == false

            - name: (GPU) install proprietary driver using dynamic kernel modules (DKMS)
              pacman:
                name: '{{ item }}'
                state: present
              with_items:
                - dkms
                - nvidia-dkms
              when: gpu_nvidia_dkms|default(false) == true
        - name: (GPU) install nvidia-settings
          pacman:
            name: nvidia-settings
            state: present
