---
- hosts: arch_linux
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - processor-detection
    - kvm
  tasks:
    - include_role:
        name: pci-passthrough
      when: pci_devices_to_isolate is defined
