---
- include_tasks: enable-service.yml
  with_items:
    - dhcpcd.service
    - sshd

- include_tasks: enable-service.yml
  with_items:
    - docker.service
  when: sys_docker|default(false) == true
