name: Arch Linux

on:
  push:
    paths:
      - 'cpp/toolchain/Dockerfile.archlinux'
  schedule:
    - cron: '0 2 * * *'

jobs:
  toolchain:
    uses: ./.github/workflows/ghcr.yml
    with:
      tag: toolchain-archlinux
      filename: cpp/toolchain/Dockerfile.archlinux
