name: Ubuntu

on:
  push:
    paths:
      - 'cpp/toolchain/Dockerfile.ubuntu'
  schedule:
    - cron: '0 2 * * *'

jobs:
  toolchain:
    uses: ./.github/workflows/ghcr.yml
    with:
      tag: toolchain-ubuntu
      filename: cpp/toolchain/Dockerfile.ubuntu
